# Generated by Django 3.0.3 on 2020-04-06 06:47

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200406_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.post_directory_path),
        ),
    ]
